name: allensdk_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.23.5
  - pandas=1.5.3
  - scipy=1.10.1
  - jupyter
  - ipykernel
  - matplotlib
  - scikit-image
  - h5py
  - pytables
  - seaborn
  - tqdm
  - pip
  - pip:
      - allensdk==2.16.2
      - pynwb==2.5.0
      - requests
      - boto3